server:
  port: 18888
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
spring:
  application:
    name: lg-picture-backend
  # 开放更大的文件上传体积
  servlet:
    multipart:
      max-file-size: 10MB
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://leocoder.cn:3306/lg_picture?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: gzm2001..
  redis:
    database: 5 # Redis 数据库索引（默认为 0）
    host: 127.0.0.1 # Redis 服务器地址
    port: 6379 # Redis 服务器连接端口
    password:   # Redis 服务器连接密码（默认为空）
    timeout: 5s # 读超时时间
    connect-timeout: 5s # 链接超时时间
    lettuce:
      pool:
        max-active: 200 # 连接池最大连接数
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0 # 连接池中的最小空闲连接
        max-idle: 10 # 连接池中的最大空闲连接
  # session 配置
  session:
    store-type: redis
    # session 30 天过期 单位秒
    timeout: 2592000
#  profiles:
#    active: local


#mybatis-plus配置
mybatis-plus:
  #配置Mapper映射文件
  mapper-locations: classpath:/mapper/*.xml
  # 配置Mybatis数据返回类型别名（默认别名为类名）
  type-aliases-package: org.leocoder.picture.domain
  configuration:
    # 自动驼峰命名
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: isDeleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)


#配置控制台打印日志Debug
logging:
  level:
    org.leocoder.picture.mapper: debug

# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: "接口文档"
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - org.leocoder.picture.controller
